### ISSUE TITLE
How do the benchmarks work?

### ISSUE THREAD

**Issue by eproxus** [williamthome/euneus#1]
I'm interested in the benchmarks presented. It is a bit unclear to me what is actually compared.

How come Euneus is faster even though it in theory does more work than Thoas? Are the benchmarks including the new Euneus encoders or not?

**Comment by williamthome** [comment]
Hi, @eproxus!
You are right, things are unclear at the moment. Improve documentation, add specs, and embed benchmarks are on the `Euneus` roadmap. I'm busy now, but I will open a PR to explain what you asked as soon as possible.
Thanks for this issue!

**Comment by williamthome** [comment]
In a nutshell, organizing the Thoas code and inlining some functions have improved the performance.
About the new encoders... yes, the new encoders option is implemented and considered in the benchmarks.

**Comment by williamthome** [comment]
I integrated benchmarks into the project.

About the optimization, rewriting Thoas allowed me to see some non-optimized code, and I believe there is more to optimize.
As I said before, the optimization comes from code organization and inlining some functions. There is no magic here :)
English is not my best, so docs may contain unclear things.

Feel free to test and bring suggestions/feedback o/

**Comment by williamthome** [comment]
In theory, `Euneus` does not do more work than `Thoas`.
Compare [Thoas](https://github.com/lpil/thoas/blob/1496f469b0b9fc724c960307529b9cce30765e35/src/thoas_encode.erl#L1720) vs [Euneus](https://github.com/williamthome/euneus/blob/c5b53f6ed75ac74f5e169c995ecbfc208a4d7b70/src/euneus_encoder.erl#L135) implementation of the value encoding. Both are just calling a function.

**Comment by williamthome** [comment]
There are a lot of updates since my last comments. 
Please see the [README](https://github.com/williamthome/euneus?tab=readme-ov-file#euneus) file and let me know if you have any additional questions or suggestions :slightly_smiling_face:
